"""change exam recode subjectid as not unique

Revision ID: 2b2253e8b75a
Revises: 9a09a7429df8
Create Date: 2024-12-26 16:53:19.285861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2253e8b75a'
down_revision = '9a09a7429df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_records', schema=None) as batch_op:
        batch_op.drop_index('subject_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_records', schema=None) as batch_op:
        batch_op.create_index('subject_id', ['subject_id'], unique=True)

    # ### end Alembic commands ###
